<?php

namespace MediaWiki\Extension\FFI\MediaWiki\ContentHandlers;

use Content;

class ScriptContent extends \AbstractContent {

	public function getTextForSearchIndex()
	{
		// TODO: Implement getTextForSearchIndex() method.
	}

	public function getWikitextForTransclusion()
	{
		// TODO: Implement getWikitextForTransclusion() method.
	}

	public function getTextForSummary($maxLength = 250)
	{
		// TODO: Implement getTextForSummary() method.
	}

	public function getNativeData()
	{
		// TODO: Implement getNativeData() method.
	}

	public function getSize()
	{
		// TODO: Implement getSize() method.
	}

	public function copy()
	{
		// TODO: Implement copy() method.
	}

	public function isCountable($hasLinks = null)
	{
		// TODO: Implement isCountable() method.
	}

	public function isValid()
	{
		return parent::isValid(); // TODO: Change the autogenerated stub
	}
}